steal(
	'../dom/animate/animate_test.js',
	'../dom/compare/compare_test.js',
	'../dom/form_params/form_params_test.js',
	'../dom/range/range_test.js',
	'../dom/selection/selection_test.js',
	'../event/drag/drag_test.js',
	'../event/drop/drop_test.js',
	'../event/hover/hover_test.js',
	'../event/key/key_test.js',
	'../event/pause/pause_test.js',
	'../event/removed/removed_test.js',
	'../event/resize/resize_test.js',
	'../event/swipe/swipe_test.js',
	'../lang/vector/vector_test.js'
);
